export const hotelReviews = [
  "Great stay! Clean rooms and friendly staff.",
  "The room was small and uncomfortable. Not worth the price.",
  "Decent hotel, but the breakfast options were limited.",
  "Superb service! The staff went out of their way to help us.",
  "The location is perfect, but the Wi-Fi was very slow.",
  "No hot water in the shower. Wouldn't recommend.",
  "Nice decor, but the noise from the street kept me up at night.",
  "Had a pleasant experience overall. Would stay again.",
  "Amazing view from the room! Highly recommend for scenic stays.",
  "Air conditioning didn’t work, and it was really hot inside.",
  "Clean and quiet hotel. Nothing fancy but good value for the price.",
  "Worst experience ever. Room was filthy and smelled bad.",
  "Very cozy and modern. Loved the comfy bed!",
  "The staff was rude and unhelpful. Very disappointing.",
  "The lobby is beautiful, but the room didn’t live up to the hype.",
  "Perfect for a short stay. Nothing extraordinary, but it works.",
  "Not much to do around the area, but the hotel itself is decent.",
  "Nice pool, but the water wasn’t as clean as it should have been.",
  "The room was spacious, but the furniture was outdated.",
  "The hotel is too expensive for what it offers. Wouldn’t return.",
  "Good location, but the elevator was always slow.",
  "Had a peaceful sleep here. Quiet area and comfy beds.",
  "Check-in was a mess, but the room was okay.",
  "Highly recommend for business trips. The conference rooms are great.",
  "The bathroom wasn’t cleaned properly. Very disappointing.",
  "Fantastic location near restaurants and shops. Will stay again!",
  "It’s a decent place if you don’t have high expectations.",
  "Had some issues with the room service, but the front desk was helpful.",
  "The hotel is outdated. Needs a renovation urgently.",
  "Great for families. Lots of kid-friendly amenities.",
  "The room was too noisy. Couldn’t sleep because of outside traffic.",
  "Average stay. Nothing special, but the bed was comfortable.",
  "The staff was incredibly helpful. 5 stars for customer service!",
  "Expensive for what you get. Room was basic and unremarkable.",
  "Very clean, but the room lacked basic amenities like a fridge.",
  "Good place for a quick stopover. Not luxurious but functional.",
  "Amazing food at the hotel restaurant. Worth trying.",
  "Room was too hot, even with the air conditioning on full blast.",
  "Staff were friendly, but the room had a musty smell.",
  "Nice hotel, but the parking was a hassle.",
  "Lovely ambiance, but I expected more luxury for the price.",
  "Good spot for tourists. Walking distance to major attractions.",
  "Room was fine, but the TV channels were limited.",
  "Hotel was decent, but the check-out process was confusing.",
  "I had a wonderful stay at the hotel.",
  "The room was spotless and the staff were friendly.",
  "Great value for money and excellent service.",
  "The location was perfect for exploring the city.",
  "Everything was clean and well maintained.",
  "Staff went above and beyond to help us.",
  "We enjoyed our time here and would come again.",
  "Fantastic experience from check-in to check-out.",
  "The bed was very comfortable and cozy.",
  "Highly recommend this place to anyone visiting.",
  "The stay was okay, nothing too special.",
  "It was average, just what we expected.",
  "Service was fine but not outstanding.",
  "The room looked exactly like the photos.",
  "Facilities were usable but not impressive.",
  "Our stay was neither great nor terrible.",
  "Just a standard hotel experience.",
  "The food was decent but nothing memorable.",
  "Okay for a quick overnight stay.",
  "An acceptable choice for the price.",
  "The room was dirty and smelled bad.",
  "Staff were rude and unhelpful during our stay.",
  "Very noisy environment, couldn’t sleep well.",
  "Poor maintenance and broken amenities.",
  "We were disappointed with the cleanliness.",
  "Definitely not worth the money we paid.",
  "Had issues with the check-in process.",
  "Would not recommend this hotel to others.",
  "The bed was uncomfortable and squeaky.",
  "Air conditioning did not work at all.",
];
